### ISSUE TITLE
Diagrama procesos postulación

### ISSUE THREAD

**Issue by EdithConfigurado** [Ciclo4-ucaldas/G8-adaptative-dev-team#12]

**Comment by JulianRDeveloper** [comment]
![Image](https://user-images.githubusercontent.com/111306904/199353472-93b28b84-b558-4645-8d71-45d024bc346e.jpg)

**Comment by JulianRDeveloper** [comment]
Eliminacion de la Entidad Postulacion.

![Image](https://user-images.githubusercontent.com/111306904/199570507-8f0fa3e7-c5fe-425c-8039-d0cce23eb04b.jpg)
