### ISSUE TITLE
Documentación Sprint 2

### ISSUE THREAD

**Issue by EdithConfigurado** [Ciclo4-ucaldas/G8-adaptative-dev-team#3]
- [x] Historias de Usuario
- [x] Diagrama Modelo de negocio
- [x] Diagrama Servicio , registro y autenticación de usuario
- [x] Diagrama de Proceso postulación 
- [x] Diagrama proceso solicitud

**Comment by JulianRDeveloper** [comment]
[Documento Proyecto MiTechoApp.pdf](https://github.com/Ciclo4-ucaldas/G8-adaptative-dev-team/files/9946801/Documento.Proyecto.MiTechoApp.pdf)
