### ISSUE TITLE
App Rest LoopBack

### ISSUE THREAD

**Issue by EdithConfigurado** [Ciclo4-ucaldas/G8-adaptative-dev-team#8]
- [x]  Creación  context MongoDB
- [x] Creación de Controladores
- [x]  Creación de Repositorios
- [x]  Creación de Modelo

**Comment by JulianRDeveloper** [comment]
- Enumeraciones Globales: No se ha podido implementar. Hasta el momento enumeraciones instanciadas localmente en el modelo.
- Context MongoBd : sin testear al momento
